# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/lovely-prompts',
                'doc_host': 'https://xl0.github.io',
                'git_url': 'https://github.com/xl0/lovely-prompts',
                'lib_path': 'lovely_prompts'},
  'syms': {'lovely_prompts.core': {'lovely_prompts.core.foo': ('core.html#foo', 'lovely_prompts/core.py')}}}
